import type { Metadata } from "next";
import { Poppins, Rubik, Work_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins'
});
const work_sans = Work_Sans({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: '--font-work_sans'
});

export const metadata: Metadata = {
  title: "Evanty",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/images/favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={work_sans.variable}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
